# Generated by Django 5.0.6 on 2024-05-29 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_reg_deadline', models.DateTimeField()),
                ('event_max_capacity', models.IntegerField()),
                ('event_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='event_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
