# Generated by Django 5.0.6 on 2024-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ems', '0003_eventinfo_event_entry_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='event_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='event_images/'),
        ),
    ]
