# Generated by Django 5.0.6 on 2024-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ems', '0004_alter_eventinfo_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='total_booking',
            field=models.IntegerField(default=0),
        ),
    ]
